server:
  port: 8082
  servlet:
    context-path: /
     
spring:
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/fb_login
    username: root
  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
         facebook:
          clientId: 810176857452592
          clientSecret: 7ad7b9c0ca28f63835eb9d7cfe56acfe
          scope:
           - email
           - public_profile  